[colors.primary]
background = "#11121D"
foreground = "#A9B1D6"

[font]
size = 14.5

[font.bold]
family = "SpaceMono Nerd Font"
style = "Bold"

[font.italic]
family = "SpaceMono Nerd Font"
style = "Oblique"

[font.normal]
family = "SpaceMono Nerd Font"
style = "Medium"

[window]
opacity = 0.8

[window.padding]
x = 0
y = 0

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 10_000
multiplier = 3

[cursor.style]
shape = "Block"
blinking = "On"

[cursor]
blink_interval = 500

[[keyboard.bindings]]
key = "Return"
mods = "Super|Shift"
action = "SpawnNewInstance"
